services:
  web:
    build: .
    container_name: planify_web
    volumes:
      - ./planify-web:/var/www/html
    ports:
      - "8080:80"
    networks:
      - planify_net

  db:
    image: mysql:8.0
    container_name: planify_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./planify-web/db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - planify_net

networks:
  planify_net:
    driver: bridge